# Generated by Django 5.1.6 on 2026-04-05 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_video', models.FileField(upload_to='videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('heatmap', models.ImageField(blank=True, null=True, upload_to='heatmaps/')),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('video_score', models.FloatField(default=0.0)),
                ('brand_score', models.FloatField(default=0.0)),
                ('video_confidence', models.FloatField(default=0.0)),
                ('brand_confidence', models.FloatField(default=0.0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('estimated_gain', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
