# Generated by Django 5.1.6 on 2026-04-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedanalysis',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedanalysis',
            name='highlights_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='uploadedanalysis',
            name='recommendations_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='uploadedanalysis',
            name='source_type',
            field=models.CharField(default='upload', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedanalysis',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
